import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RateLimitDisplay from "../components/RateLimitDisplay";

/**
 * RootLayout component for the application.
 * @param children - The children of the RootLayout component.
 * @returns The RootLayout component.
 */

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * GeistMono font for the application.
 */

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Metadata for the application.
 */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout component for the application.
 * @param children - The children of the RootLayout component.
 * @returns The RootLayout component.
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <RateLimitDisplay />
      </body>
    </html>
  );
}
